import Head from "next/head";
import Header from "../components/Header";
import { BsThreeDotsVertical, BsFillFolderSymlinkFill } from "react-icons/bs";
import { IconButton } from "@material-tailwind/react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getSession, useSession } from "next-auth/react";
import Login from "../components/Login";
import {
  Button,
  Dialog,
  DialogHeader,
  DialogBody,
  DialogFooter,
} from "@material-tailwind/react";
import { useState } from "react";
import { db } from "../firebase.config";
import { doc, setDoc, getDoc, onSnapshot } from "firebase/firestore";
import {
  useCollectionOnce,
  useDocumentData,
} from "react-firebase-hooks/firestore";
import DocumentRow from "../components/DocumentRow";

function Home() {
  const { data: session } = useSession();
  console.log(session, " session");

  // {
  //   session && alert("He");
  // }

  const [showModal, setShowModal] = useState(false);
  const [input, setInput] = useState("");

  console.log(db, "db");
  const handleOpen = () => setShowModal(false);
  const createDocumnet = () => {
    if (!input) return;
    const myDocRef = doc(db, "docs", "userDocs");
    setDoc(
      myDocRef,
      {
        name: input,
      },
      { merge: true }
    );
    // setInput("");
    setShowModal(false);
  };

  // unsub();
  // console.log(unsub, "UNSSS");
  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Google Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="bg-[#F8F9FA] px-10 pb-10">
        <div className="max-w-3xl mx-auto">
          <div className=" flex items-center justify-between py-6">
            <h2 className="text-grey-700 text-lg">Start a new document</h2>
            <IconButton size="lg" variant="text" className="bottom-0 ">
              <BsThreeDotsVertical color="grey" />
            </IconButton>
          </div>
          <div className="relative h-52 w-40 cursor-pointer hover:shadow-md">
            <Image
              src="https://links.papareact.com/pju"
              layout="fill"
              onClick={() => setShowModal(true)}
            />
          </div>
          <p className="ml-2 mt-2 font-semibold text-grey-700">Blank</p>
        </div>
      </section>
      <section className="bg-grey-200 px-10 md:px-0">
        <div className="max-w-3xl mx-auto py-8 text-grey-700">
          <div className="flex items-center justify-between pb-5">
            <h2>My Documnets</h2>
            <p>Date Created</p>
            <BsFillFolderSymlinkFill color="gray" />
          </div>
        </div>
        <DocumentRow input={input} />
      </section>
      <Dialog open={showModal} handler={handleOpen}>
        <DialogBody divider>
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Enter name of document"
            className="outline-none w-full"
            onKeyDown={(e) => e.key === "Enter" && createDocumnet()}
          />
        </DialogBody>
        <DialogFooter>
          <Button
            variant="text"
            // color="red"
            onClick={handleOpen}
            className="mr-1"
          >
            <span>Cancel</span>
          </Button>
          <Button variant="gradient" color="blue" onClick={createDocumnet}>
            <span>Confirm</span>
          </Button>
        </DialogFooter>
      </Dialog>
    </div>
  );
}
export async function getServerSideProps(context) {
  console.log(context, "C");
  const session = await getSession(context);
  return {
    props: { session }, // will be passed to the page component as props
  };
}

export default Home;
